### ISSUE TITLE
Ignore template files starting with a dot

### ISSUE THREAD

**Issue by Blesmol** [Blesmol/pfsct#38]
Files where the filename starts with a dot (".foo.yml") are considered hidden by some OSes and should be ignored,

**Comment by tdhsmith** [comment]
Think it should also be trying to handle Windows' hidden files, or just force the Unix standard on everybody? (If the latter, it seems like all you need is a regexp tweak in YamlFile.go)

**Comment by Blesmol** [comment]
> Think it should also be trying to handle Windows' hidden files

Definitely not, I currently do not see a reason for this.

> If the latter, it seems like all you need is a regexp tweak in YamlFile.go

Yes, thats the way to go. Just didn't do it so far.

Main motivation here for me was that while working on a file some editors like good ole emacs might put temporary copies into the same directory as the original file, and then I was getting error messages when running pfscf at that time. Will sooner or later drop a fix for this.
